version: '3.8'

services:
  web:
    build: .
    ports:
      - "${APP_PORT}:80"
    volumes:
      - ./index.php/var/www/html/index.php
    environment:
      - APACHE_RUN_USER=www-data
      - APACHE_RUN_GROUP=www-data