version: '3.8'

services:
  web:
    build: .
    ports:
      - "${APP_PORT}:80"
    volumes:
      - ./index.php/var/www/html/index.php
    environment:
      - db

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d # init SQL 

phpmyadmin:
  image: phpmyadmin/phpmyadmin
  restart: always
  ports:
    - "${PHPMYADMIN_PORT}:80"
  environment:
    PMA_HOST: db
    MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}


volumes:
  db_data: